### ISSUE TITLE
Tracks play out of order in a strange way in my "favorites" folder

### ISSUE THREAD

**Issue by birdybro** [AidanHockey5/MegaBlaster2#11]
I have made a favorites folder which has a bunch of songs in it. If I play them in order it's all over the place for some reason. I think having lots of files might be causing issues (much like how many many folders kept giving me a strange manifest previously before you scrapped the manifest system. When I select the first song, which is `01 - Rise From Your Grave.vgm` (Altered Beast) it says it is `Track: 357/376` but it should be the first one (as selected, but it's actually 14th alphabetically). Then when I go to the next track it heads to `04 - There Is No Time To Lose.vgm` (Herzog Zwei) and says it is on `Track: 358/376`. Heading back a track to 357 again actually sends me back to `01 - Jagd Flieger` (from Herzog Zwei again). 

https://we.tl/t-TsjDRPsZ5M - Zip of the vgm files in my `/_Favorites` folder so you can test it out on your own.

Normally I play things shuffled in this folder so it's not a major problem to me, but just thought it was something worth mentioning. Even what is seen as the first track when I navigate to the folder, actually should be the 14th track.

**Comment by AidanHockey5** [comment]
Fixed as of [this commit](https://github.com/AidanHockey5/MegaBlaster2/commit/ae5be3b58f98205448724ec183efc40a433b3bba)

Firmware download: https://github.com/AidanHockey5/MegaBlaster2/releases/tag/1.22

Thank you!
