### ISSUE TITLE
Loops: 1 = Loops: 0 and Loops: 0 just instantly switches through tracks.

### ISSUE THREAD

**Issue by birdybro** [AidanHockey5/MegaBlaster2#8]
Title kinda says it all. When I set Loops to 0, this ends up just cycling through tracks rapidly, sort of like it's `loops: -1` or something like that. If I set loops to 1, it acts as though there is no loop.

**Comment by AidanHockey5** [comment]
That’s a fairly easy fix. I’ll just set the minimum loop value to 1 instead
of zero. Good catch!

**Comment by AidanHockey5** [comment]
[Fixed here](https://github.com/AidanHockey5/MegaBlaster2/commit/b9249292348143ee4603d3a3c36aa7a3937c46f3), thank you!
